name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install node
      uses: actions/setup-node@v2-beta
      with:
          node-version: '14'

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install

    - name: Lint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run test

    - name: Build
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run build
